[project]
name = "habittracker"
version = "0.1.0"
description = "Habit Tracker - трекер полезных привычек"
authors = [
    {name = "Агеева Софья",email = "son4a1996@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django==6.0.7",
    "djangorestframework==3.17.1",
    "djangorestframework-simplejwt==5.4.0",
    "drf-yasg==1.21.8",
    "django-cors-headers==4.7.0",
    "django-filter==25.1",
    "celery==5.6.3",
    "redis==5.0.1",
    "psycopg2-binary==2.9.9",
    "python-dotenv==1.1.1",
    "coverage==7.15.3",
    "requests==2.31.0",

]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
