# Generated by Django 6.1 on 2026-08-13 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='От 1 до 7 дней', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (дни)')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(help_text='Не более 120 секунд', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (сек)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_habit', models.ForeignKey(blank=True, help_text='Может быть только приятной привычкой', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
    ]
