# Generated by Django 6.0.7 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
